apiVersion: v1
kind: Secret
metadata:
  name: gshub-secrets
  namespace: gshub
type: Opaque
stringData:
  db-password: "password"
  jwt-secret: "secret"
  mailersend-api-key: "replace-me"
  stripe-secret-key: "replace-me"
  stripe-webhook-secret: "replace-me"
  tunnel-token: "replace-me"